### ISSUE TITLE
Increase number of simulated reads in sample or custom mode

### ISSUE THREAD

**Issue by JBerthelier** [ConesaLab/SQANTI-SIM#8]
Dear SQUATI-SIM author,

I am using your tool to simulate the needed number of reads to cover most of the transcripts of the transcriptome of my organism of interest, by drawing a read rarefaction curve. 

here my questions:

Do there are any ways to increase the number of simulated reads keeping the same distribution TPM with the mode sample / custom? 

I do not understand if giving the option -nt 1,000,000 could help me simulating 1M reads ?

or maybe should I do multiple run and concatenate the reads obtained to increase the number?

Best reagards, 

Jeremy

**Comment by jmestret** [comment]
Hi Jeremy,

Thank you for reaching out and for using SQANTI-SIM!

Although you could run SQANTI-SIM multiple times, there's no need to do that in your case. By tuning the `-nt/--trans_number` argument, you'll be selecting the number of different isoforms to simulate. And using the `--long_count` argument, you will define the total number of reads to simulate. So, in order to simulate 1M reads, you should set `--long_count` to `1000000`.

Now, the way SQANTI-SIM distributes these reads between the simulated isoforms can be customized. For example, by using the **sample** mode, the TPM distribution will be based on a real provided sample, whereas in **custom** mode you can specify two different count distributions with various parameters: one for the novel isoforms and one for the known isoforms.

For example, in this code from Supplementary File 3 of the SQANTI-SIM paper (https://doi.org/10.1186/s13059-023-03127-0), we simulated a total of 50,000 different isoforms, of which 15,000 were novel (5,000 ISM, 5,000 NIC, and 5,000 NNC). We simulated **4,000,000** PacBio reads using the sample mode, following the count distribution of the default pre-trained data:

```bash
python sqanti - sim . py full - sim sample \
    -- gtf $annotation \
    -- genome $genome \
    -d $pb_dir \
    -- pb -- illumina -- CAGE \
    -- iso_complex -- diff_exp 2 \
    -- trans_number 50000 \
    -- ISM 5000 -- NIC 5000 -- NNC 5000 \
    -- long_count 4000000 \
    -- short_count 60000000 \
    -k 8 -- seed 3654
```

You can also provide a custom distribution by using the `--expr_file` or `--long_reads` arguments.

I hope this information is helpful!

Best regards,  
Jorge :)

**Comment by JBerthelier** [comment]
Dear Jorge, 
Thanks for your reply, it help me to increase the numer of reads :)
Best regards!
